### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by piever** [GodotNativeTools/godot_headers#11]
Is this functionality supported on Mac OS? I've run the README test.c example, after changing:

```
#include <godot/gdnative.h>
#include <godot_nativescript.h>
```

to 

```
#include <gdnative/gdnative.h>
#include <nativescript/godot_nativescript.h>
```

as it seems the header files have been moved.

If I run the compilation commands I get:

```
macbook-pro:simplelibrary pietro$ clang -g -fPIC -std=c99 -c src/test.c -Igodot_headers -o src/test.os
macbook-pro:simplelibrary pietro$ clang -g -shared src/test.os
Undefined symbols for architecture x86_64:
  "_godot_nativescript_register_class", referenced from:
      _godot_nativescript_init in test.os
  "_godot_nativescript_register_method", referenced from:
      _godot_nativescript_init in test.os
  "_godot_print", referenced from:
      _some_test_procedure in test.os
  "_godot_string_destroy", referenced from:
      _some_test_procedure in test.os
  "_godot_string_new_unicode_data", referenced from:
      _some_test_procedure in test.os
  "_godot_variant_new_int", referenced from:
      _some_test_procedure in test.os
  "_godot_variant_new_nil", referenced from:
      _test_ready in test.os
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And the outpu with `-v` is:

```
macbook-pro:simplelibrary pietro$ clang -g -v -shared src/test.os
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -dylib -arch x86_64 -macosx_version_min 10.12.0 -o a.out src/test.os -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_godot_nativescript_register_class", referenced from:
      _godot_nativescript_init in test.os
  "_godot_nativescript_register_method", referenced from:
      _godot_nativescript_init in test.os
  "_godot_print", referenced from:
      _some_test_procedure in test.os
  "_godot_string_destroy", referenced from:
      _some_test_procedure in test.os
  "_godot_string_new_unicode_data", referenced from:
      _some_test_procedure in test.os
  "_godot_variant_new_int", referenced from:
      _some_test_procedure in test.os
  "_godot_variant_new_nil", referenced from:
      _test_ready in test.os
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm on latest master of Godot and godot_headers.

I really don't understand the error as for example `godot_nativescript_register_class` is defined in the godot_nativescript.h header.

Is there something that needs to be changed to the compilation commands for them to work on Mac OS?

**Comment by karroffel** [comment]
@BastiaanOlij got it working on Mac OS I think, you need to tell the linker to not care about those unresolved symbols some how. I will change things in GDNative itself in the next few days so these problems won't even come up again.

**Comment by piever** [comment]
Thanks in advance for that! And kudos for developing this functionality, it looks very promising.

**Comment by 1l0** [comment]
Try those linker flags for now:
`-Wl, -undefined dynamic_lookup`

**Comment by piever** [comment]
Thanks!
Also, shoud I give

`clang -g -shared -Wl -undefined dynamic_lookup src/test.os -o lib/test.dylib
`
rather than 

`clang -g -shared -Wl -undefined dynamic_lookup src/test.os -o lib/test.so`

?

**Comment by piever** [comment]
I can compile with no errors with the new flags, but when trying the example in the README I get:

```
Method function failed, returning: ERR_CANT_RESOLVE

C source: drivers/unix/os_unix.cpp: 423
C function: get_dynamic_library_symbol_handle
```

I've executed the previous command with `-o lib/test.dylib` as I can only select dylib from godot gdnative resource (which makes sense on a mac).

**Comment by 1l0** [comment]
Try this:
`clang -g -shared -framework Cocoa -Wl,-undefined,dynamic_lookup your_file.os -o your_file.dylib`

**Comment by piever** [comment]
Same error... Any idea what the error means and why for example Cocoa could help?

**Comment by BastiaanOlij** [comment]
Owh I gottah find some time tonight, been pretty flat out with my day job as we had a public holiday on Monday and I'm catching up:)

I remember we had this issue first time around when we tried compiling on mac but those switches "-Wl,-undefined,dynamic_lookup" were what fixed it last time.

**Comment by 1l0** [comment]
@piever That's just what I have done previously and succeeded on Godot 3.0a but tons of commits are added since then so no idea your situation. At least I could say that Godot is not ready for production and not comfortable on macOS yet.

**Comment by piever** [comment]
I see, if it's so much in flux I should probably wait at least for the next alpha build to try and get it to work.

**Comment by piever** [comment]
UPDATE: actually with the correct flags and rechecking the project structure I got it to print 42 (not the greatest achievement, but still). Thanks a lot for the help! If I see that it works reliably it'd be probably good to update the README to add mac support.

**Comment by BastiaanOlij** [comment]
Hey @piever ,

Just fork this repository and put a PR in with an updated readme. The best obviously is updating the scons files:)

I hope to have time this weekend to dive back into this because I want to start on my project for porting the VR PRs to GDNative so I'll be trying to finish off on getting some of my sample projects up and running on both Windows and Mac (I don't have access to a Linux machine unfortunately atm).

**Comment by piever** [comment]
Hi @BastiaanOlij , scons is really beyond my expertise but I can make a PR later today updating the README with the solution that worked for me.

The problem is not fully solved though, as the toy example in the README can be made to work, but I couldn't manage to bind an external library (which I guess is the whole point of GDNative...). I'll try to post a MWE soon to reproduce the issue. Please keep me posted if you manage to bind external C/C++ libraries with GDNative on a Mac.

**Comment by BastiaanOlij** [comment]
Hey @piever, scons is worth learning :)

I hope to have time for this over the weekend. Linking in an external library shouldn't be hard but it depends on how the external library has been written. In theory is should be just a matter of adding the library to the link command.

**Comment by BastiaanOlij** [comment]
@piever , have a look at:
https://github.com/GodotNativeTools/GDNative-demos/pull/8

With the latest changes @karroffel made things have become a lot simpler. Only issue right now is that this repo needs to be updated so the latest API struct is available or you'll run into a few issues but that will be taken care off shortly.

**Comment by karroffel** [comment]
I think this can be closed. Correct me if I'm wrong 😄
