### ISSUE TITLE
godot_net.h includes reference types

### ISSUE THREAD

**Issue by Xenoprimate** [GodotNativeTools/godot_headers#39]
I believe the header files are meant to be C-compatible, but godot_net.h includes reference types (for example `int &r_received` on line 54).

Means I can not compile C code using GDNative if I want to `#include "net/godot_net.h"`

**Comment by karroffel** [comment]
Indeed! @faless probably overlooked that when creating the C headers

**Comment by BastiaanOlij** [comment]
I updated the files based on Godot 3.1 stable, did that get these changes included? if so this issue is probably resolved.

**Comment by Faless** [comment]
@BastiaanOlij yep, that was merged before `3.1` release, and the changes are already there in the `3.1` branch:
https://github.com/GodotNativeTools/godot_headers/blob/3.1/net/godot_net.h

The issue can be closed

**Comment by BastiaanOlij** [comment]
Perfect!
