### ISSUE TITLE
godot_native_terminate: Can't resolve symbol

### ISSUE THREAD

**Issue by capnm** [GodotNativeTools/godot_headers#4]
```
ERROR: get_dynamic_library_symbol_handle: Can't resolve symbol godot_native_terminate.
 Error: xxxx.so: undefined symbol: godot_native_terminate
   At: drivers/unix/os_unix.cpp:465.
```
That should be either in the docs as mandatory or fixed in the code.

**Comment by karroffel** [comment]
what docs? :^)

---------

This error actually isn't an error. `godot_native_terminate` is completely optional, but `get_dynamic_library_symbol_handle` prints an error when it's not present. So this isn't actually an error but a warning. It's a philosophical question whether to keep it an error or not.

I could *require* such a function, but it's useless oftentimes. So yeah, for now just ignore that warning.

If you *do* want to implement that function, the signature is

`void GDN_EXPORT godot_native_terminate(godot_native_terminate_options *);`

--------------

Either way, this isn't an issue with the headers but with Godot, so please open an issue there, but documentation will clear this up in future.

**Comment by capnm** [comment]
Ok, then your FAQ :-)

If it's intended as optional, it shouldn't trigger any warnings or errors. Law of sanity ;)
BTW terminate is called 2x – if that's feature, should be mentioned in the docs/FAQ.

**Comment by karroffel** [comment]
Huh, it should only be called once, will investigate that

**Comment by capnm** [comment]
Sorry, false alarm ;) My debug output got intermixed with the calls from the godot tool GUI.
The init <-> terminate count is ok.

**Comment by karroffel** [comment]
Oh awesome, I started sweating for a minute 😄
