### ISSUE TITLE
Win10 VS2015-built DLL: Fails to load GDNativeLibrary

### ISSUE THREAD

**Issue by willnationsdev** [GodotNativeTools/godot_headers#5]
**Context:**
Windows 10
Visual Studio 2015 Community Edition
Godot latest as of commit `ceded65` from 06/20/2017
Having just compiled a .dll in visual studio (walkthrough in [this issue from /cpp_bindings](https://github.com/GodotNativeTools/cpp_bindings/issues/12).

**Issue:**
Built the cpp_bindings tutorial SimpleClass into the .dll. SimpleClass has no parent class it inherits from as far as the scripting language is concerned (?).
Attempting to load the .gdn resource after setting it to point towards the .tres of the GDNativeLibrary appears to fail with the following errors:

`Can't open dynamic library: [path to project_folder/lib/gdtestdll.dll] Error: 126`
`Condition ' initialize_status != OK ' is true.`
`Condition ' !native_library->scripts.has(p_name) ' is true. returned: 0`
`Condition ' !script_data ' is true.`

**Reproducible Steps:**

1. Create a godot project. In this case I'll reference `GDNativeTest` as the project name and project_folder name.

2. Create `lib` folder and insert into it the .dll file generated from visual studio project build (referenced above).

3. Create Node2D as root node in first scene. Save scene as `main.tscn` in `GDNativeTest`.

4. Click on the Add Resource button, select GDNativeLibrary. Set the "Windows" file to be `GDNativeTest/lib/gdtestdll.dll`. Save it as `GDNativeTest/gdtestdll.tres`.

5. Click on the Add Resource button, select GDNativeScript. Set the target to be `GDNativeTest/gdtestdll.tres`. Set the Class Name to "SimpleClass".

6. Add a built in GDScript inheriting from Node2D to the root node. Add, below the extends statement, the following:

`var SimpleClass = preload("res://SimpleClass.gdn")`

7. Run the game. The errors discussed initially will display in the debugger. Attempting to call more functions, such as

`func _ready():`
`    var sc = SimpleClass.new()`

...will result in an error as new() is considered a nonexistent function.

**Comment by karroffel** [comment]
[Error description](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx)

Windows is ***reeeeally*** bad at telling you what the problem is.

Let me guess, you have all the dlls in the `lib/` folder?
Put the `godot_cpp_core.dll` and `godot_cpp_bindings.dll` in the *Godot project root*. Then it should work. The `gdtestdll.dll` can stay in `lib/`

**Comment by willnationsdev** [comment]
Actually, I didn't have the other .dll's in there at all!

Tried adding `godot_cpp_core.dll` and `godot_cpp_bindings.dll` to the `GDNativeTest` project root and that didn't work. Then I tried moving them into the `GDNativeTest/lib` folder to be next to the other `gdtestdll.dll` and that didn't work either. I also tried closing and re-opening the engine before each attempt and neither of those worked either.

**Comment by karroffel** [comment]
Weird, that should work. Windows just can't look up dll dependencies in subfolders (at least not implicitly)

**Comment by willnationsdev** [comment]
Created a different project that literally just throws everything into the root godot project directory. I have the following:

`.import` (folder)
`default_env.tres`
`gdtestdll.dll`
`gdtestdll.exp`
`gdtestdll.ilk`
`gdtestdll.lib`
`gdtestdll.pdb`
`gdtestdll.tres`
`godot_cpp_bindings.dll`
`godot_cpp_bindings.exp`
`godot_cpp_bindings.lib`
`godot_cpp_core.dll`
`godot_cpp_core.exp`
`godot_cpp_core.lib`
`icon.png`
`icon.png.import`
`main.tscn`
`project.godot`
`SimpleClass.gdn`

main.tscn has a single Node2D with a GDScript that simply preload's "res://SimpleClass.gdn" as described before.

`SimpleClass.gdn` is pointing to `gdtestdll.tres` which in turn has its Windows value set to `gdtestdll.dll`

Still getting the same error.

**Comment by karroffel** [comment]
Oh, I just noticed that this is the wrong repository, try opening that one on the cpp_bindings repo
