### ISSUE TITLE
How to document pure C NativeScript/GDNative?

### ISSUE THREAD

**Issue by ngasull** [GodotNativeTools/godot_headers#61]
Hi everybody !

I really want to document the native C module I'm developing right now, just like the rest of Godot's main API is documented.

I've [noticed in godot_headers](https://github.com/GodotNativeTools/godot_headers/blob/master/gdnative_api_struct.gen.h#L64 "noticed in godot_headers") functions that are supposed achieve that, in particular:
- `godot_nativescript_set_method_argument_information`
- `godot_nativescript_set_method_documentation`

However they are not accessible from `godot_gdnative_ext_nativescript_api_struct` which seems to be the only one exposed to the C API. Or at least, it's the only one explained in the little documentation/tutorials for godot native C libs so far. These functions would perfectly fit my desire to integrate in Godot a lib that is made to be used by others. 

I deliberately avoid C++ API because it's much heavier and I don't like the idea of having a 50MB library just because I have to bundle all the godot-cpp static libraries (if you have a solution for this by the way I'm interested :))

So: **What is the solution right now to document the methods I register through C API? Is it possible and how?**

Thank you!  <3 

_(NB: I've [posted this in Godot Forums](https://godotforums.org/discussion/21713/how-to-document-pure-c-nativescript-gdnative) as well and will keep both sides updated)_

**Comment by karroffel** [comment]
I don't think this information is used inside the editor yet in any way, so I think it is not too useful at the moment. The way to access those functions is via the `next` field of `godot_gdnative_ext_nativescript_api_struct`. If the extension version is 1.1 then this `next` field has to be casted to `godot_gdnative_ext_nativescript_1_1_api_struct`. Then you can access the functions.

**Comment by ngasull** [comment]
Oh, I could access those function through `next` indeed! But it didn't register any docs, indeed...

That feature would be really dope though, and would for sure boost Godot's dev community! But one thing goes at a time, and your work on the native API is extremely appreciated @karroffel :smiley: I might join to help once I'm better used to Godot's ecosystem.

Thank you for your accurate feedback!
