### ISSUE TITLE
Native scripts crash on Windows with MinGW

### ISSUE THREAD

**Issue by msik314** [GodotNativeTools/godot_headers#7]
Whenever I try to call any Godot function from a native script, the scene or engine crashes depending on which is trying to use it.  I should mention, that I am not trying to cross compile from Linux, but rather building on Windows with MinGW-w64.

**Comment by karroffel** [comment]
I haven't tested anything on mingw yet as getting MSVC working was of higher priortiy. I will look into that but can't promise when.

Do you use a MinGW build of Godot and a MinGW build of your library?

**Comment by msik314** [comment]
I have used both the prebuilt binary and a MinGW build of Godot.   I have built the engine, but I don't know how to build the library myself..

**Comment by msik314** [comment]
I can confirm this is a compiler compatibility issue.  I found a tool that converts MSVC libraries to MinGW compatible ones, and after conversion, everything worked fine.
